diff --git a/src/Makefile b/src/Makefile
index ba0627a..281f550 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -1,13 +1,15 @@
-CC= gcc
+# CC= gcc
+CC= emcc
 RM= rm -f
-AR= ar
+# AR= ar
+AR= emar
 LN= ln -sfn
 CP= cp
 MKDIR = mkdir -p
 
 LIBVER=0.6
 LIBMAINVER=0
-FLAGS= -Wall -O3 -fomit-frame-pointer -fpic -Winline 
+FLAGS= -Werror -Wall -O3 -fomit-frame-pointer -fpic -Winline
 
 prefix = /usr
 exec_prefix = ${prefix}
